__author__ = "Gergely Wootsch"
__copyright__ = "Copyright 2017, Gergely Wootsch"
__credits__ = ["Studio AKA", "Gergely Wootsch"]
__license__ = "GPL"
__version__ = "0.5.0"
__modified__ = "25/10/2017"
__maintainer__ = "Gergely Wootsch"
__email__ = "hello@gergely-wootsch.com"
__status__ = "Production"
