script = """init = (function(){
    var path =  '<UV_Image_Path>'
    var texture_name = '<Texture_PSD_Name>';
    var fileIn = new File(path);
    app.open(fileIn);
    function doAction(){
        var idsetd = charIDToTypeID( 'setd' );
            var desc3 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref1 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                var idBckg = charIDToTypeID( 'Bckg' );
                ref1.putProperty( idLyr, idBckg );
            desc3.putReference( idnull, ref1 );
            var idT = charIDToTypeID( 'T   ' );
                var desc4 = new ActionDescriptor();
                var idNm = charIDToTypeID( 'Nm  ' );
                desc4.putString( idNm, 'uvMask' );
                var idOpct = charIDToTypeID( 'Opct' );
                var idPrc = charIDToTypeID( '#Prc' );
                desc4.putUnitDouble( idOpct, idPrc, 100.000000 );
                var idMd = charIDToTypeID( 'Md  ' );
                var idBlnM = charIDToTypeID( 'BlnM' );
                var idNrml = charIDToTypeID( 'Nrml' );
                desc4.putEnumerated( idMd, idBlnM, idNrml );
            var idLyr = charIDToTypeID( 'Lyr ' );
            desc3.putObject( idT, idLyr, desc4 );
            var idLyrI = charIDToTypeID( 'LyrI' );
            desc3.putInteger( idLyrI, 2 );
        executeAction( idsetd, desc3, DialogModes.NO );
        // =======================================================
        var idsetd = charIDToTypeID( 'setd' );
            var desc5 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref2 = new ActionReference();
                var idChnl = charIDToTypeID( 'Chnl' );
                var idfsel = charIDToTypeID( 'fsel' );
                ref2.putProperty( idChnl, idfsel );
            desc5.putReference( idnull, ref2 );
            var idT = charIDToTypeID( 'T   ' );
            var idOrdn = charIDToTypeID( 'Ordn' );
            var idAl = charIDToTypeID( 'Al  ' );
            desc5.putEnumerated( idT, idOrdn, idAl );
        executeAction( idsetd, desc5, DialogModes.NO );
        // =======================================================
        var idcopy = charIDToTypeID( 'copy' );
        executeAction( idcopy, undefined, DialogModes.NO );
        // =======================================================
        var idMk = charIDToTypeID( 'Mk  ' );
            var desc6 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref3 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                ref3.putClass( idLyr );
            desc6.putReference( idnull, ref3 );
            var idLyrI = charIDToTypeID( 'LyrI' );
            desc6.putInteger( idLyrI, 3 );
        executeAction( idMk, desc6, DialogModes.NO );
        // =======================================================
        var idsetd = charIDToTypeID( 'setd' );
            var desc7 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref4 = new ActionReference();
                var idPrpr = charIDToTypeID( 'Prpr' );
                var idQucM = charIDToTypeID( 'QucM' );
                ref4.putProperty( idPrpr, idQucM );
                var idDcmn = charIDToTypeID( 'Dcmn' );
                var idOrdn = charIDToTypeID( 'Ordn' );
                var idTrgt = charIDToTypeID( 'Trgt' );
                ref4.putEnumerated( idDcmn, idOrdn, idTrgt );
            desc7.putReference( idnull, ref4 );
        executeAction( idsetd, desc7, DialogModes.NO );
        // =======================================================
        var idpast = charIDToTypeID( 'past' );
            var desc8 = new ActionDescriptor();
            var idinPlace = stringIDToTypeID( 'inPlace' );
            desc8.putBoolean( idinPlace, true );
            var idAntA = charIDToTypeID( 'AntA' );
            var idAnnt = charIDToTypeID( 'Annt' );
            var idAnno = charIDToTypeID( 'Anno' );
            desc8.putEnumerated( idAntA, idAnnt, idAnno );
            var idAs = charIDToTypeID( 'As  ' );
            var idPxel = charIDToTypeID( 'Pxel' );
            desc8.putClass( idAs, idPxel );
        executeAction( idpast, desc8, DialogModes.NO );
        // =======================================================
        var idCler = charIDToTypeID( 'Cler' );
            var desc9 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref5 = new ActionReference();
                var idPrpr = charIDToTypeID( 'Prpr' );
                var idQucM = charIDToTypeID( 'QucM' );
                ref5.putProperty( idPrpr, idQucM );
                var idDcmn = charIDToTypeID( 'Dcmn' );
                var idOrdn = charIDToTypeID( 'Ordn' );
                var idTrgt = charIDToTypeID( 'Trgt' );
                ref5.putEnumerated( idDcmn, idOrdn, idTrgt );
            desc9.putReference( idnull, ref5 );
        executeAction( idCler, desc9, DialogModes.NO );
        // =======================================================
        var idMk = charIDToTypeID( 'Mk  ' );
            var desc10 = new ActionDescriptor();
            var idNw = charIDToTypeID( 'Nw  ' );
            var idChnl = charIDToTypeID( 'Chnl' );
            desc10.putClass( idNw, idChnl );
            var idAt = charIDToTypeID( 'At  ' );
                var ref6 = new ActionReference();
                var idChnl = charIDToTypeID( 'Chnl' );
                var idChnl = charIDToTypeID( 'Chnl' );
                var idMsk = charIDToTypeID( 'Msk ' );
                ref6.putEnumerated( idChnl, idChnl, idMsk );
            desc10.putReference( idAt, ref6 );
            var idUsng = charIDToTypeID( 'Usng' );
            var idUsrM = charIDToTypeID( 'UsrM' );
            var idRvlS = charIDToTypeID( 'RvlS' );
            desc10.putEnumerated( idUsng, idUsrM, idRvlS );
        executeAction( idMk, desc10, DialogModes.NO );
        // =======================================================
        var idslct = charIDToTypeID( 'slct' );
            var desc11 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref7 = new ActionReference();
                var idChnl = charIDToTypeID( 'Chnl' );
                var idChnl = charIDToTypeID( 'Chnl' );
                var idRGB = charIDToTypeID( 'RGB ' );
                ref7.putEnumerated( idChnl, idChnl, idRGB );
            desc11.putReference( idnull, ref7 );
            var idMkVs = charIDToTypeID( 'MkVs' );
            desc11.putBoolean( idMkVs, false );
        executeAction( idslct, desc11, DialogModes.NO );
        // =======================================================
        var idsetd = charIDToTypeID( 'setd' );
            var desc12 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref8 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                var idOrdn = charIDToTypeID( 'Ordn' );
                var idTrgt = charIDToTypeID( 'Trgt' );
                ref8.putEnumerated( idLyr, idOrdn, idTrgt );
            desc12.putReference( idnull, ref8 );
            var idT = charIDToTypeID( 'T   ' );
                var desc13 = new ActionDescriptor();
                var idNm = charIDToTypeID( 'Nm  ' );
                desc13.putString( idNm, 'uvs' );
            var idLyr = charIDToTypeID( 'Lyr ' );
            desc12.putObject( idT, idLyr, desc13 );
        executeAction( idsetd, desc12, DialogModes.NO );
        // =======================================================
        var idRset = charIDToTypeID( 'Rset' );
            var desc14 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref9 = new ActionReference();
                var idClr = charIDToTypeID( 'Clr ' );
                var idClrs = charIDToTypeID( 'Clrs' );
                ref9.putProperty( idClr, idClrs );
            desc14.putReference( idnull, ref9 );
        executeAction( idRset, desc14, DialogModes.NO );
        // =======================================================
        var idExch = charIDToTypeID( 'Exch' );
            var desc15 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref10 = new ActionReference();
                var idClr = charIDToTypeID( 'Clr ' );
                var idClrs = charIDToTypeID( 'Clrs' );
                ref10.putProperty( idClr, idClrs );
            desc15.putReference( idnull, ref10 );
        executeAction( idExch, desc15, DialogModes.NO );
        // =======================================================
        var idExch = charIDToTypeID( 'Exch' );
            var desc16 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref11 = new ActionReference();
                var idClr = charIDToTypeID( 'Clr ' );
                var idClrs = charIDToTypeID( 'Clrs' );
                ref11.putProperty( idClr, idClrs );
            desc16.putReference( idnull, ref11 );
        executeAction( idExch, desc16, DialogModes.NO );
        // =======================================================
        var idsetd = charIDToTypeID( 'setd' );
            var desc17 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref12 = new ActionReference();
                var idClr = charIDToTypeID( 'Clr ' );
                var idFrgC = charIDToTypeID( 'FrgC' );
                ref12.putProperty( idClr, idFrgC );
            desc17.putReference( idnull, ref12 );
            var idT = charIDToTypeID( 'T   ' );
                var desc18 = new ActionDescriptor();
                var idH = charIDToTypeID( 'H   ' );
                var idAng = charIDToTypeID( '#Ang' );
                desc18.putUnitDouble( idH, idAng, 0.000000 );
                var idStrt = charIDToTypeID( 'Strt' );
                desc18.putDouble( idStrt, 100.000000 );
                var idBrgh = charIDToTypeID( 'Brgh' );
                desc18.putDouble( idBrgh, 100.000000 );
            var idHSBC = charIDToTypeID( 'HSBC' );
            desc17.putObject( idT, idHSBC, desc18 );
            var idSrce = charIDToTypeID( 'Srce' );
            desc17.putString( idSrce, 'colorPickerPanel' );
        executeAction( idsetd, desc17, DialogModes.NO );
        // =======================================================
        var idFl = charIDToTypeID( 'Fl  ' );
            var desc19 = new ActionDescriptor();
            var idUsng = charIDToTypeID( 'Usng' );
            var idFlCn = charIDToTypeID( 'FlCn' );
            var idFrgC = charIDToTypeID( 'FrgC' );
            desc19.putEnumerated( idUsng, idFlCn, idFrgC );
        executeAction( idFl, desc19, DialogModes.NO );
        // =======================================================
        var idslct = charIDToTypeID( 'slct' );
            var desc23 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref13 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                ref13.putName( idLyr, 'uvMask' );
            desc23.putReference( idnull, ref13 );
            var idMkVs = charIDToTypeID( 'MkVs' );
            desc23.putBoolean( idMkVs, false );
            var idLyrI = charIDToTypeID( 'LyrI' );
                var list1 = new ActionList();
                list1.putInteger( 2 );
            desc23.putList( idLyrI, list1 );
        executeAction( idslct, desc23, DialogModes.NO );
        // =======================================================
        var idDlt = charIDToTypeID( 'Dlt ' );
            var desc24 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref14 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                var idOrdn = charIDToTypeID( 'Ordn' );
                var idTrgt = charIDToTypeID( 'Trgt' );
                ref14.putEnumerated( idLyr, idOrdn, idTrgt );
            desc24.putReference( idnull, ref14 );
            var idLyrI = charIDToTypeID( 'LyrI' );
                var list2 = new ActionList();
                list2.putInteger( 2 );
            desc24.putList( idLyrI, list2 );
        executeAction( idDlt, desc24, DialogModes.NO );
        // Duplicate layer into document
        // =======================================================
        var idDplc = charIDToTypeID( 'Dplc' );
            var desc61 = new ActionDescriptor();
            var idnull = charIDToTypeID( 'null' );
                var ref37 = new ActionReference();
                var idLyr = charIDToTypeID( 'Lyr ' );
                var idOrdn = charIDToTypeID( 'Ordn' );
                var idTrgt = charIDToTypeID( 'Trgt' );
                ref37.putEnumerated( idLyr, idOrdn, idTrgt );
            desc61.putReference( idnull, ref37 );
            var idT = charIDToTypeID( 'T   ' );
                var ref38 = new ActionReference();
                var idDcmn = charIDToTypeID( 'Dcmn' );
                ref38.putName( idDcmn, texture_name );
            desc61.putReference( idT, ref38 );
            var idNm = charIDToTypeID( 'Nm  ' );
            desc61.putString( idNm, 'uvs' );
            var idVrsn = charIDToTypeID( 'Vrsn' );
            desc61.putInteger( idVrsn, 5 );
            var idIdnt = charIDToTypeID( 'Idnt' );
                var list5 = new ActionList();
                list5.putInteger( 6 );
            desc61.putList( idIdnt, list5 );
        executeAction( idDplc, desc61, DialogModes.NO );
        // =======================================================
        var idCls = charIDToTypeID( 'Cls ' );
            var desc80 = new ActionDescriptor();
            var idSvng = charIDToTypeID( 'Svng' );
            var idYsN = charIDToTypeID( 'YsN ' );
            var idN = charIDToTypeID( 'N   ' );
            desc80.putEnumerated( idSvng, idYsN, idN );
            var idDocI = charIDToTypeID( 'DocI' );
            desc80.putInteger( idDocI, 266 );
            var idforceNotify = stringIDToTypeID( 'forceNotify' );
            desc80.putBoolean( idforceNotify, true );
        executeAction( idCls, desc80, DialogModes.NO );
    }
    doAction()
})()"""
